### ISSUE TITLE
ur software is still busted...

### ISSUE THREAD

**Issue by tomammon** [boabdilperez/snake_game#2]
─ ./main.py 
from: can't read /var/mail/scoreboard
from: can't read /var/mail/food
from: can't read /var/mail/snake
from: can't read /var/mail/turtle
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
./main.py: 7: Syntax error: "(" unexpected

**Comment by tomammon** [comment]
it's _obviously_ not a problem with my local environment

;-)

**Comment by boabdilperez** [comment]
After 4 years of extensive research and development, I have fixed the import issues with the snake game. thank you for your patience.

**Comment by tomammon** [comment]
Excellent. Now I can build my unicorn software startup on your back. But don't worry, I'll be sure to come back here to harass you, dear open source maintainer, should anything go wrong in the future. 

;-)
